### ISSUE TITLE
CORS ERROR

### ISSUE THREAD

**Issue by Umar94** [adyen-examples/adyen-php-online-payments#14]
Access to fetch at 'https://checkoutshopper-test.adyen.com/checkoutshopper/v1/sessions/CSDBF5B97DD1E1355B/setup?clientKey=test_KBE3NOA7Q5ACFEMPRYBV5BKNZ4VHIRBM' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by nicolasros** [comment]
Hi Umar94,
if it is still relevant, I had the same issue for a moment because I forgot to add my origin to the "Allowed Origins".
Adding it immediately solved the CORS issue.

**Comment by jlengrand** [comment]
Thanks for the answer @nicolasros . That's indeed one of the most logical reasons
