### ISSUE TITLE
Internet Explorer 11 Problem

### ISSUE THREAD

**Issue by simogrima** [adyen-examples/adyen-php-online-payments#15]
adyenImplementation.js have problem on Internet Explorer 11
IE11 non support async, promise and URLSearchParams

**Comment by jlengrand** [comment]
Hey there! 

That is correct. Internet Explorer is becoming legacy and this sample tries to stay simple for most users.

If you want to be running this sample on IE11, you'll most likely have to transpile to ES5 and possibly add polyfills.
