### ISSUE TITLE
Getting 403 on payments. Is missing ADYEN_HMAC_KEY the problem ?

### ISSUE THREAD

**Issue by tarach** [adyen-examples/adyen-php-online-payments#25]
Hello,

When I'm trying to pay with one of the test CCs I get 403 as a response.

I've filled ADYEN_API_KEY, ADYEN_MERCHANT_ACCOUNT, ADYEN_CLIENT_KEY
I've also added the user to all accounts and tried multiple different combinations of roles.

![image](https://user-images.githubusercontent.com/351514/169952697-a4fd093d-3b41-4ff3-9fb9-68693a6f56ac.png)

1. What are the correct roles ?
2. What should the ADYEN_HMAC_KEY be set to ?

**Comment by jlengrand** [comment]
Hey @tarach, 

The ADYEN_HMAC_KEY is only used for webhooks, so it won't trigger a 403. If you indeed have all roles set, could you please double check that the environment variables are indeed picked up by the application and that you have set your allowed origin properly ( https://docs.adyen.com/development-resources/client-side-authentication#allowed-origins)?

If that doesn't help, I'll need some more information (the complete back and front end error messages) so I can check further

**Comment by tarach** [comment]
Yes environment variables are being read. I've tested by injecting 
`die(json_encode(getenv(), JSON_PRETTY_PRINT));`
into AdyenClient constructor. I've also regenerated the api key and tried again. 
Allowed origin is also set to http://127.0.0.1:8080
![image](https://user-images.githubusercontent.com/351514/170002405-9dd8973c-95b0-4515-8ccb-d5914c3717b6.png)

**Comment by tarach** [comment]
@jlengrand 

https://user-images.githubusercontent.com/351514/170007948-00a191e7-5e79-43da-9f6e-337bfaa2355d.mp4

**Comment by tarach** [comment]
Creating new User API Credentials solved the issue.
